import { TCategory } from "./types";

export const dataSet: TCategory[] = [
  {
    id: "category_1",
    name: {
      he: "הצלחת הראשונה",
      en: "Starters",
      ru: "Закуски",
      fr: "Entrées",
      ar: "المقبلات",
    },
    description: {
      he: "מבחר מנות ראשונות ופתיחים",
      en: "Selection of appetizers and openers",
      ru: "Выбор закусок и стартеров",
      fr: "Sélection d'entrées et amuse-bouches",
      ar: "مجموعة من المقبلات والفواتح",
    },
    order: 2,
    thumbnail:
      "https://images.immediate.co.uk/production/volatile/sites/30/2024/03/Jamon-and-wild-garlic-croquetas-50f2d2f.jpg",
    dishes: [
      {
        id: "dish_1_1",
        name: {
          he: "פוקצ'ה על אבן",
          en: "Stone-Baked Focaccia",
          ru: "Фокачча на камне",
          fr: "Focaccia sur pierre",
          ar: "فوكاتشا على الحجر",
        },
        description: {
          he: "שמן שום, פטרוזיליה, מטבל סלסת עגבניות, שמן זית ובלסמי",
          en: "Garlic oil, parsley, tomato salsa dip, olive oil & balsamic",
          ru: "Чесночное масло, петрушка, томатная сальса, оливковое масло и бальзамик",
          fr: "Huile d'ail, persil, dip salsa tomate, huile d'olive et balsamique",
          ar: "زيت ثوم، بقدونس، صلصة طماطم، زيت زيتون وبلسمك",
        },
        price: 34,
      },
      {
        id: "dish_1_2",
        name: {
          he: "חציל ים תיכוני",
          en: "Mediterranean Eggplant",
          ru: "Средиземноморский баклажан",
          fr: "Aubergine méditerranéenne",
          ar: "باذنجان متوسطي",
        },
        description: {
          he: "חציל על האבן בליווי טחינה, סלסת עגבניות טריות, שמן זית, פטרוזיליה",
          en: "Stone-grilled eggplant with tahini, fresh tomato salsa, olive oil, parsley",
          ru: "Баклажан на камне с тахини, свежей томатной сальсой, оливковым маслом, петрушкой",
          fr: "Aubergine sur pierre avec tahini, salsa tomate fraîche, huile d'olive, persil",
          ar: "باذنجان على الحجر مع طحينية، صلصة طماطم طازجة، زيت زيتون وبقدونس",
        },
        price: 44,
      },
      {
        id: "dish_1_3",
        name: {
          he: "נשנוש חלומי קראנצ'י",
          en: "Crunchy Halloumi Bites",
          ru: "Хрустящий халуми",
          fr: "Bouchées de halloumi croustillantes",
          ar: "قطع حلوم مقرمشة",
        },
        description: {
          he: "אצבעות חלומי מטוגנות בזיגוג טריאקי ושומשום",
          en: "Fried halloumi fingers in teriyaki glaze & sesame",
          ru: "Жареные палочки халуми в глазури терияки с кунжутом",
          fr: "Doigts de halloumi frits, glaze teriyaki et sésame",
          ar: "أصابع حلوم مقلية بصلصة تيرياكي وسمسم",
        },
        price: 59,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0032.jpg",
      },
      {
        id: "dish_1_4",
        name: {
          he: "סלט קפרזה",
          en: "Caprese Salad",
          ru: "Капрезе",
          fr: "Salade caprese",
          ar: "سلطة كابريزي",
        },
        description: {
          he: "קרעי גבינת מוצרלה, עגבניות שרי, בצל סגול, בזיליקום, בלסמי מצומצם ומלח גס",
          en: "Fresh mozzarella, cherry tomatoes, purple onion, basil, balsamic reduction & sea salt",
          ru: "Свежая моцарелла, помидоры черри, фиолетовый лук, базилик, бальзамическая редукция и морская соль",
          fr: "Mozzarella fraîche, tomates cerises, oignon violet, basilic, réduction balsamique et sel gros",
          ar: "موزاريلا طازجة، طماطم كرز، بصل أرجواني، ريحان، بلسمك مركز وملح خشن",
        },
        price: 59,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_9914.jpg",
      },
      {
        id: "dish_1_5",
        name: {
          he: "ארטישוק א-לה רומנה",
          en: "Artichoke alla Romana",
          ru: "Артишок по-римски",
          fr: "Artichaut à la romaine",
          ar: "أرضي شوكي على الطريقة الرومانية",
        },
        description: {
          he: "ארטישוק צלוי על הגריל, עגבניות שרי מוקפצות עם בצל ופלפל חריף, פרמון, בלסמי מצומצם, שום קונפי ומלח גס",
          en: "Grilled artichoke, sautéed cherry tomatoes with onion and hot pepper, parmesan, balsamic reduction, garlic confit & sea salt",
          ru: "Жареный артишок, тушеные помидоры черри с луком и острым перцем, пармезан, бальзамическая редукция, чесночный конфи и морская соль",
          fr: "Artichaut grillé, tomates cerises sautées avec oignon et piment, parmesan, réduction balsamique, confit d'ail et sel gros",
          ar: "أرضي شوكي مشوي، طماطم كرز مقلية مع بصل وفلفل حار، بارميزان، بلسمك مركز، ثوم كونفي وملح خشن",
        },
        price: 59,
        spicy: true,
        recommended: true,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0037.jpg",
      },
      {
        id: "dish_1_6",
        name: {
          he: "עלי גפן",
          en: "Stuffed Grape Leaves",
          ru: "Долма",
          fr: "Feuilles de vigne farcies",
          ar: "ورق عنب محشي",
        },
        description: {
          he: "5 יח' עלי גפן במילוי אורז לבן בהכנה ביתית, חומש על לאבנה עם שמן זית",
          en: "5 pcs homemade grape leaves stuffed with white rice, served on labneh with olive oil",
          ru: "5 шт. домашней долмы с белым рисом, подается на лабне с оливковым маслом",
          fr: "5 pcs feuilles de vigne maison farcies au riz blanc, servies sur labneh avec huile d'olive",
          ar: "5 حبات ورق عنب محشي بالأرز الأبيض محضر منزلياً، يقدم على اللبنة مع زيت الزيتون",
        },
        price: 59,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_9977.jpg",
      },
      {
        id: "dish_1_7",
        name: {
          he: "כנפיים פריכות",
          en: "Crispy Wings",
          ru: "Хрустящие крылышки",
          fr: "Ailes croustillantes",
          ar: "أجنحة مقرمشة",
        },
        description: {
          he: "כנפי עוף בציפוי פריך מוקפצות ברוטב מתקתק מוגש עם שומשום ובצל ירוק",
          en: "Crispy-coated chicken wings in sweet-tangy sauce, served with sesame & green onion",
          ru: "Куриные крылышки в хрустящей панировке в сладко-остром соусе с кунжутом и зелёным луком",
          fr: "Ailes de poulet enrobées croustillantes dans une sauce douce-piquante, servies avec sésame et oignon vert",
          ar: "أجنحة دجاج مغطاة مقرمشة في صلصة حلوة لاذعة، تقدم مع سمسم وبصل أخضر",
        },
        price: 62,
      },
      {
        id: "dish_1_8",
        name: {
          he: "סמוסה",
          en: "Samosas",
          ru: "Самосы",
          fr: "Samosas",
          ar: "سمبوسك",
        },
        description: {
          he: "5 יח' סמוסות בהכנה ביתית, 5 יחי בצק פילו במילוי עוף טחון מתובל בטעמים הודיים, מוגש עם רוטב צ'אטני",
          en: "5 pcs homemade samosas, phyllo dough filled with spiced ground chicken in Indian flavors, served with chutney sauce",
          ru: "5 шт. домашние самосы, тесто фило с пряным фаршем из курицы в индийском стиле, подается с чатни",
          fr: "5 pcs samosas maison, pâte phyllo garnie de poulet haché épicé aux saveurs indiennes, servi avec sauce chutney",
          ar: "5 حبات سمبوسك محضر منزلياً، عجينة فيلو محشوة بدجاج مفروم متبل بنكهات هندية، يقدم مع صلصة شاتني",
        },
        price: 62,
      },
      {
        id: "dish_1_9",
        name: {
          he: "צ'יפס קלאסי",
          en: "Classic Fries",
          ru: "Классический картофель фри",
          fr: "Frites classiques",
          ar: "بطاطا مقلية كلاسيكية",
        },
        description: {
          he: "צ'יפס קלאסי פריך (תוספת בולגרית 15)",
          en: "Crispy classic fries (Bulgarian cheese add 15)",
          ru: "Хрустящий классический картофель фри (добавка болгарского сыра 15)",
          fr: "Frites classiques croustillantes (supplément fromage bulgare 15)",
          ar: "بطاطا مقلية كلاسيكية مقرمشة (إضافة جبنة بلغارية 15)",
        },
        price: 47,
      },
      {
        id: "dish_1_10",
        name: {
          he: "חומוס טחינה",
          en: "Hummus & Tahini",
          ru: "Хумус и тахини",
          fr: "Houmous et tahini",
          ar: "حمص وطحينة",
        },
        description: {
          he: "חומוס, טחינה ביתית, פפריקה אדומה, שמן זית ופטרוזיליה. מוגש עם 2 פיתות",
          en: "Hummus, homemade tahini, paprika, olive oil & parsley. Served with 2 pitas",
          ru: "Хумус, домашняя тахини, паприка, оливковое масло и петрушка. Подается с 2 питами",
          fr: "Houmous, tahini maison, paprika, huile d'olive et persil. Servi avec 2 pitas",
          ar: "حمص، طحينة منزلية، بابريكا، زيت زيتون وبقدونس. يقدم مع 2 خبز بيتا",
        },
        price: 38,
      },
      {
        id: "dish_1_11",
        name: {
          he: "כרובית",
          en: "Cauliflower",
          ru: "Цветная капуста",
          fr: "Chou-fleur",
          ar: "قرنبيط",
        },
        description: {
          he: "כרובית מטוגנת בציפוי קריספי בליווי צ'ילי מתוק",
          en: "Fried cauliflower in crispy coating with sweet chili",
          ru: "Жареная цветная капуста в хрустящей панировке со сладким чили",
          fr: "Chou-fleur frit enrobage croustillant avec chili doux",
          ar: "قرنبيط مقلي بطبقة مقرمشة مع صلصة تشيلي حلوة",
        },
        price: 47,
      },
      {
        id: "dish_1_12",
        name: {
          he: "שניצלונים",
          en: "Chicken Strips",
          ru: "Куриные полоски",
          fr: "Filets de poulet panés",
          ar: "أصابع دجاج",
        },
        description: {
          he: "רצועות עוף בציפוי פריך",
          en: "Crispy-coated chicken strips",
          ru: "Куриные полоски в хрустящей панировке",
          fr: "Filets de poulet enrobés croustillants",
          ar: "شرائح دجاج مغطاة بطبقة مقرمشة",
        },
        price: 59,
      },
      {
        id: "dish_1_13",
        name: {
          he: "אדממה",
          en: "Edamame",
          ru: "Эдамаме",
          fr: "Edamame",
          ar: "إدامامي",
        },
        description: {
          he: "פולי סויה מבושלים עם מלח גס ולימון",
          en: "Boiled soybeans with sea salt & lemon",
          ru: "Отварные соевые бобы с морской солью и лимоном",
          fr: "Graines de soja bouillies avec sel gros et citron",
          ar: "فول الصويا مسلوق مع ملح خشن وليمون",
        },
        price: 45,
      },
      {
        id: "dish_1_14",
        name: {
          he: "רביולי סלק",
          en: "Beet Ravioli",
          ru: "Равиоли из свеклы",
          fr: "Raviolis de betterave",
          ar: "رافيولي الشمندر",
        },
        description: {
          he: "גבינת מסקרפונה עיזים מטוגנת בליווי רוטב שמנת וגבינות בצד, 4 יחידות",
          en: "Fried goat mascarpone ravioli with cream & cheese sauce on the side, 4 pcs",
          ru: "Жареные равиоли с козьим маскарпоне и соусом из сливок и сыра, 4 шт",
          fr: "Raviolis mascarpone de chèvre frits avec sauce crème et fromage à côté, 4 pcs",
          ar: "رافيولي جبن ماسكاربوني ماعز مقلي مع صلصة كريمة وجبن جانباً، 4 حبات",
        },
        price: 59,
        recommended: true,
      },
      {
        id: "dish_1_15",
        name: {
          he: "קרפצ'יו סלק",
          en: "Beet Carpaccio",
          ru: "Карпаччо из свеклы",
          fr: "Carpaccio de betterave",
          ar: "كارباتشيو الشمندر",
        },
        description: {
          he: "דבש, בלסמי מצומצם, מלח, שמן זית, עלי בייבי, גבינת פטה",
          en: "Honey, balsamic reduction, salt, olive oil, baby greens, feta cheese",
          ru: "Мёд, бальзамическая редукция, соль, оливковое масло, молодая зелень, сыр фета",
          fr: "Miel, réduction balsamique, sel, huile d'olive, jeunes pousses, fromage feta",
          ar: "عسل، بلسمك مركز، ملح، زيت زيتون، أوراق خضراء صغيرة، جبنة فيتا",
        },
        price: 59,
        recommended: true,
      },
    ],
  },
  {
    id: "category_2",
    name: {
      he: "עיקריות",
      en: "Main Courses",
      ru: "Основные блюда",
      fr: "Plats principaux",
      ar: "الأطباق الرئيسية",
    },
    description: {
      he: "מוגש עם תוספת אחת לבחירה - סלט אישי / צ'יפס / אורז",
      en: "Served with one side of your choice - personal salad / fries / rice",
      ru: "Подается с одним гарниром на выбор - персональный салат / картофель фри / рис",
      fr: "Servi avec un accompagnement au choix - salade individuelle / frites / riz",
      ar: "يقدم مع طبق جانبي واحد من اختيارك - سلطة فردية / بطاطا مقلية / أرز",
    },
    order: 5,
    dishes: [
      {
        id: "dish_2_1",
        name: {
          he: "פרגית עסיסית",
          en: "Juicy Chicken Thigh",
          ru: "Сочная куриная ножка",
          fr: "Cuisse de poulet juteuse",
          ar: "فخذ دجاج طري",
        },
        description: {
          he: "פרגית עוף בגריל, מושרה בתערובת תבלינים",
          en: "Grilled chicken thigh, marinated in spice blend",
          ru: "Куриная ножка на гриле, маринованная в смеси специй",
          fr: "Cuisse de poulet grillée, marinée dans un mélange d'épices",
          ar: "فخذ دجاج مشوي، متبل بمزيج التوابل",
        },
        price: 89,
      },
      {
        id: "dish_2_2",
        name: {
          he: "קבב על פוקאצ'ה",
          en: "Kebab on Focaccia",
          ru: "Кебаб на фокачче",
          fr: "Kebab sur focaccia",
          ar: "كباب على فوكاتشا",
        },
        description: {
          he: "תערובת בשר בקר מתובל טחון, טחינה צבעונית וסלסת עגבניות",
          en: "Spiced ground beef blend, colorful tahini & tomato salsa",
          ru: "Смесь пряного фарша из говядины, цветная тахини и томатная сальса",
          fr: "Mélange de bœuf haché épicé, tahini coloré et salsa tomate",
          ar: "مزيج لحم بقر مفروم متبل، طحينة ملونة وصلصة طماطم",
        },
        price: 119,
      },
      {
        id: "dish_2_3",
        name: {
          he: "שניצל הבית",
          en: "House Schnitzel",
          ru: "Домашний шницель",
          fr: "Escalope maison",
          ar: "شنيتسل البيت",
        },
        description: {
          he: "חזה עוף מתובל מצופה בפירורים פריכים",
          en: "Seasoned chicken breast coated in crispy breadcrumbs",
          ru: "Приправленная куриная грудка в хрустящей панировке",
          fr: "Blanc de poulet assaisonné enrobé de chapelure croustillante",
          ar: "صدر دجاج متبل مغطى بفتات الخبز المقرمش",
        },
        price: 82,
      },
      {
        id: "dish_2_4",
        name: {
          he: "נקניקיות מרגז חריפות",
          en: "Spicy Merguez Sausages",
          ru: "Острые колбаски мергез",
          fr: "Saucisses merguez épicées",
          ar: "نقانق مرجز حارة",
        },
        description: {
          he: "נקניקיות מרגז פיזנטיות בליווי טחינה",
          en: "Peasant-style merguez sausages with tahini",
          ru: "Колбаски мергез в деревенском стиле с тахини",
          fr: "Saucisses merguez paysannes avec tahini",
          ar: "نقانق مرجز ريفية مع طحينة",
        },
        price: 79,
        spicy: true,
      },
      {
        id: "dish_2_5",
        name: {
          he: "סטייק אנטריקוט",
          en: "Entrecôte Steak",
          ru: "Стейк антрекот",
          fr: "Entrecôte",
          ar: "ستيك أنتركوت",
        },
        description: {
          he: "אנטריקוס ארגנטינאי פרימיום 300 גרם",
          en: "Premium Argentine entrecôte 300g",
          ru: "Премиальный аргентинский антрекот 300г",
          fr: "Entrecôte argentine premium 300g",
          ar: "أنتركوت أرجنتيني فاخر 300 غرام",
        },
        price: 159,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/dish_2_5.jpg",
      },
      {
        id: "dish_2_6",
        name: {
          he: "פיש & צ'יפס",
          en: "Fish & Chips",
          ru: "Рыба с картошкой",
          fr: "Fish & chips",
          ar: "سمك وبطاطا",
        },
        description: {
          he: "נגסי פילה דג אמנון בציפוי טמפורה",
          en: "Tilapia fillet bites in tempura coating",
          ru: "Кусочки филе тилапии в темпурной панировке",
          fr: "Bouchées de filet de tilapia en tempura",
          ar: "قطع فيليه سمك البلطي بطبقة تمبورا",
        },
        price: 89,
      },
      {
        id: "dish_2_7",
        name: {
          he: "המבורגר אנטריקוט",
          en: "Entrecôte Burger",
          ru: "Бургер из антрекота",
          fr: "Burger entrecôte",
          ar: "برجر أنتركوت",
        },
        description: {
          he: "220 גרם בשר אנטריקוט טחון מוגש בלחמניית המבורגר עם ירקות וציפס\nתוספות: ביצת עין / בצל מטוגן / פטריות",
          en: "220g ground entrecôte served in burger bun with vegetables and fries\nAdd-ons: fried egg / fried onion / mushrooms",
          ru: "220г фарша антрекот на булочке для бургера с овощами и картошкой фри\nДобавки: яичница / жареный лук / грибы",
          fr: "220g d'entrecôte hachée servi dans un pain burger avec légumes et frites\nSuppléments : œuf au plat / oignon frit / champignons",
          ar: "220 غرام لحم أنتركوت مفروم يقدم في خبز برجر مع خضار وبطاطا\nإضافات: بيضة مقلية / بصل مقلي / فطر",
        },
        price: 89,
        recommended: true,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/dish_2_7.jpg",
      },
      {
        id: "dish_2_8",
        name: {
          he: "פלטת בשרים זוגית",
          en: "Mixed Grill Platter for Two",
          ru: "Мясное ассорти на двоих",
          fr: "Plateau mixte grillé pour deux",
          ar: "طبق مشاوي مشكل للإثنين",
        },
        description: {
          he: "אנטריקוט, 2 יח' קבב, 2 יח' מרגז, 2 יח' פרגית, 4 יח' כנפיים\nמוגש עם שתי תוספות לבחירה",
          en: "Entrecôte, 2 kebabs, 2 merguez, 2 chicken thighs, 4 wings\nServed with two sides of your choice",
          ru: "Антрекот, 2 кебаба, 2 мергеза, 2 куриные ножки, 4 крылышка\nПодается с двумя гарнирами на выбор",
          fr: "Entrecôte, 2 kebabs, 2 merguez, 2 cuisses de poulet, 4 ailes\nServi avec deux accompagnements au choix",
          ar: "أنتركوت، 2 كباب، 2 مرجز، 2 فخذ دجاج، 4 أجنحة\nيقدم مع طبقين جانبيين من اختيارك",
        },
        price: 279,
      },
      {
        id: "dish_2_9",
        name: {
          he: "כריך רוסטביף",
          en: "Roast Beef Sandwich",
          ru: "Сэндвич с ростбифом",
          fr: "Sandwich rosbif",
          ar: "ساندويتش روست بيف",
        },
        description: {
          he: "חסה, עגבנייה, מלפפון חמוץ, איולי שום וריבת בצל\nלחם לבן / דגנים לבחירה",
          en: "Lettuce, tomato, pickle, garlic aioli & onion jam\nWhite / whole grain bread",
          ru: "Салат, помидор, маринованный огурец, чесночный айоли и луковый джем\nБелый / цельнозерновой хлеб",
          fr: "Laitue, tomate, cornichon, aïoli à l'ail et confiture d'oignon\nPain blanc / céréales complètes",
          ar: "خس، طماطم، مخلل، أيولي ثوم ومربى بصل\nخبز أبيض / حبوب كاملة",
        },
        price: 79,
        recommended: true,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/dish_2_9.jpg",
      },
    ],
  },
  {
    id: "category_3",
    name: {
      he: "פינה לילדים",
      en: "Kids' Corner",
      ru: "Детское меню",
      fr: "Menu enfants",
      ar: "قائمة الأطفال",
    },
    description: {
      he: "אוכל שהילדים תמיד אוהבים",
      en: "Food kids always love",
      ru: "Еда, которую дети всегда любят",
      fr: "Nourriture que les enfants adorent",
      ar: "طعام يحبه الأطفال دائماً",
    },
    order: 5.1,
    dishes: [
      {
        id: "dish_3_1",
        name: {
          he: "אצבעות שניצל",
          en: "Schnitzel Fingers",
          ru: "Шницель палочками",
          fr: "Doigts de schnitzel",
          ar: "أصابع شنيتسل",
        },
        description: {
          he: "מוגש עם צ׳יפס",
          en: "Served with fries",
          ru: "Подается с картошкой фри",
          fr: "Servi avec frites",
          ar: "يقدم مع بطاطا مقلية",
        },
        price: 59,
      },
      {
        id: "dish_3_2",
        name: {
          he: "נקניקיות עוף",
          en: "Chicken Sausages",
          ru: "Куриные сосиски",
          fr: "Saucisses de poulet",
          ar: "نقانق دجاج",
        },
        description: {
          he: "מוגש עם צ׳יפס",
          en: "Served with fries",
          ru: "Подается с картошкой фри",
          fr: "Servi avec frites",
          ar: "يقدم مع بطاطا مقلية",
        },
        price: 59,
      },
    ],
  },
  {
    id: "category_4",
    name: {
      he: "בוקר טוב",
      en: "Breakfast",
      ru: "Завтрак",
      fr: "Petit-déjeuner",
      ar: "فطور",
    },
    description: {
      he: "מוגש עד 13:00 בימים ראשון - שישי, עד 12:00 בימי שבת",
      en: "Served until 1:00 PM Sun-Fri, until 12:00 PM on Saturdays",
      ru: "Подается до 13:00 вс-пт, до 12:00 по субботам",
      fr: "Servi jusqu'à 13h00 dim-ven, jusqu'à 12h00 le samedi",
      ar: "يُقدم حتى 1:00 مساءً من الأحد-الجمعة، حتى 12:00 ظهراً أيام السبت",
    },
    order: 1,
    thumbnail:
      "https://images.contentstack.io/v3/assets/bltcedd8dbd5891265b/bltff83a08b0ab08cb4/664cbe0dece86b22ce53e9bc/breakfast-meat-spread.jpg",
    dishes: [
      {
        id: "dish_4_1",
        name: {
          he: "ארוחת בוקר ישראלית ליחיד",
          en: "Israeli Breakfast for One",
          ru: "Израильский завтрак на одного",
          fr: "Petit-déjeuner israélien individuel",
          ar: "فطور إسرائيلي للفرد",
        },
        description: {
          he: "3 ביצים לבחירה, גבינת שמנת, גבינת פטה, סלט טונה, טחינה, אבוקדו, סלט ירוק, לחם, חמאה, ריבה\n2 שתייה חמה או קלה לבחירה.",
          en: "3 eggs your choice, cream cheese, feta, tuna salad, tahini, avocado, green salad, bread, butter, jam\n2 hot or cold drinks of your choice",
          ru: "3 яйца на выбор, сливочный сыр, фета, салат с тунцом, тахини, авокадо, зелёный салат, хлеб, масло, джем\n2 горячих или холодных напитка на выбор",
          fr: "3 œufs au choix, cream cheese, feta, salade de thon, tahini, avocat, salade verte, pain, beurre, confiture\n2 boissons chaudes ou froides au choix",
          ar: "3 بيضات حسب اختيارك، كريم تشيز، فيتا، سلطة تونة، طحينة، أفوكادو، سلطة خضراء، خبز، زبدة، مربى\n2 مشروب ساخن أو بارد من اختيارك",
        },
        price: 89,
      },
      {
        id: "dish_4_15",
        name: {
          he: "ארוחת בוקר ישראלית לזוג",
          en: "Israeli Breakfast for Two",
          ru: "Израильский завтрак на двоих",
          fr: "Petit-déjeuner israélien pour deux",
          ar: "فطور إسرائيلي للإثنين",
        },
        description: {
          he: "6 ביצים לבחירה, גבינת שמנת, גבינת פטה, סלט טונה, טחינה, אבוקדו, סלט ירוק, לחם, חמאה, ריבה\n4 שתייה חמה או קלה לבחירה.",
          en: "6 eggs your choice, cream cheese, feta, tuna salad, tahini, avocado, green salad, bread, butter, jam\n4 hot or cold drinks of your choice",
          ru: "6 яиц на выбор, сливочный сыр, фета, салат с тунцом, тахини, авокадо, зелёный салат, хлеб, масло, джем\n4 горячих или холодных напитка на выбор",
          fr: "6 œufs au choix, cream cheese, feta, salade de thon, tahini, avocat, salade verte, pain, beurre, confiture\n4 boissons chaudes ou froides au choix",
          ar: "6 بيضات حسب اختيارك، كريم تشيز، فيتا، سلطة تونة، طحينة، أفوكادو، سلطة خضراء، خبز، زبدة، مربى\n4 مشروب ساخن أو بارد من اختيارك",
        },
        price: 149,
      },
      {
        id: "dish_4_2",
        name: {
          he: "קוראסון סלמון",
          en: "Salmon Croissant",
          ru: "Круассан с лососем",
          fr: "Croissant au saumon",
          ar: "كرواسون سلمون",
        },
        description: {
          he: "קוראסון חמאה, סלמון מעושן, ביצה עלומה, שמנת, חסה ובצל",
          en: "Butter croissant, smoked salmon, poached egg, cream, lettuce & onion",
          ru: "Масляный круассан, копчёный лосось, яйцо пашот, сливки, салат и лук",
          fr: "Croissant au beurre, saumon fumé, œuf poché, crème, laitue et oignon",
          ar: "كرواسون زبدة، سلمون مدخن، بيضة مسلوقة، كريمة، خس وبصل",
        },
        price: 67,
        recommended: true,
      },
      {
        id: "dish_4_25",
        name: {
          he: "אגז בנדיקט",
          en: "Eggs Benedict",
          ru: "Яйца бенедикт",
          fr: "Œufs Bénédicte",
          ar: "بيض بنديكت",
        },
        description: {
          he: "לחם בריוש, סלמון מעושן, אבוקדו, ביצה עלומה וסלט ירוק",
          en: "Brioche bread, smoked salmon, avocado, poached egg & green salad",
          ru: "Бриошь, копчёный лосось, авокадо, яйцо пашот и зелёный салат",
          fr: "Pain brioche, saumon fumé, avocat, œuf poché et salade verte",
          ar: "خبز بريوش، سلمون مدخن، أفوكادو، بيضة مسلوقة وسلطة خضراء",
        },
        price: 79,
        recommended: true,
      },
      {
        id: "dish_4_3",
        name: {
          he: "שקשוקת הבית",
          en: "House Shakshuka",
          ru: "Домашняя шакшука",
          fr: "Shakshuka maison",
          ar: "شكشوكة البيت",
        },
        description: {
          he: "3 ביצים בתבשיל עגבניות טריות בבישול ארוך. מוגש עם טחינה, זיתים מתובלים ולחם מחמצת",
          en: "3 eggs in slow-cooked fresh tomato stew. Served with tahini, marinated olives & sourdough bread",
          ru: "3 яйца в тушёных свежих помидорах длительного приготовления. Подается с тахини, маринованными оливками и хлебом на закваске",
          fr: "3 œufs dans un ragoût de tomates fraîches longuement cuites. Servi avec tahini, olives marinées et pain au levain",
          ar: "3 بيضات في صلصة طماطم طازجة مطبوخة ببطء. يقدم مع طحينة، زيتون متبل وخبز حامض",
        },
        price: 72,
      },
      {
        id: "dish_4_4",
        name: {
          he: "שקשוקה יוונית",
          en: "Greek Shakshuka",
          ru: "Греческая шакшука",
          fr: "Shakshuka grecque",
          ar: "شكشوكة يونانية",
        },
        description: {
          he: "3 ביצים בתבשיל עגבניות טריות בבישול ארוך, בולגרית מגורדת, זיתי קלמטה",
          en: "3 eggs in slow-cooked fresh tomato stew, shredded Bulgarian cheese, Kalamata olives",
          ru: "3 яйца в тушёных свежих помидорах, тёртый болгарский сыр, оливки каламата",
          fr: "3 œufs dans un ragoût de tomates fraîches, fromage bulgare râpé, olives Kalamata",
          ar: "3 بيضات في صلصة طماطم طازجة، جبنة بلغارية مبشورة، زيتون كالاماتا",
        },
        price: 75,
      },
      {
        id: "dish_4_5",
        name: {
          he: "שקשוקה מרגז",
          en: "Merguez Shakshuka",
          ru: "Шакшука с мергезом",
          fr: "Shakshuka merguez",
          ar: "شكشوكة مرجز",
        },
        description: {
          he: "3 ביצים בתבשיל עגבניות טריות בבישול ארוך, בתוספת נקניקיות מרגז צלויות",
          en: "3 eggs in slow-cooked fresh tomato stew, with grilled merguez sausages",
          ru: "3 яйца в тушёных свежих помидорах с жареными колбасками мергез",
          fr: "3 œufs dans un ragoût de tomates fraîches, avec saucisses merguez grillées",
          ar: "3 بيضات في صلصة طماطم طازجة مع نقانق مرجز مشوية",
        },
        price: 75,
        spicy: true,
      },
      {
        id: "dish_4_6",
        name: {
          he: "בייגל טוסט צהובה",
          en: "Yellow Cheese Bagel Toast",
          ru: "Тост багель с жёлтым сыром",
          fr: "Bagel toast au fromage jaune",
          ar: "توست بيغل بالجبن الأصفر",
        },
        description: {
          he: "מוגש בתוספת סלט קטן. תוספות לבחירה: פטה, שמנת, ביצה קשה, זיתים, בצל, פטריות, תירס (6 ש״ח)\nמוגש בכל שעות היום",
          en: "Served with small salad. Optional add-ons: feta, cream, hard-boiled egg, olives, onion, mushrooms, corn (6 NIS)\nServed all day",
          ru: "Подается с небольшим салатом. Опции: фета, сливки, вареное яйцо, оливки, лук, грибы, кукуруза (6 шек.)\nПодается весь день",
          fr: "Servi avec petite salade. Options: feta, crème, œuf dur, olives, oignon, champignons, maïs (6 NIS)\nServi toute la journée",
          ar: "يقدم مع سلطة صغيرة. إضافات اختيارية: فيتا، كريمة، بيضة مسلوقة، زيتون، بصل، فطر، ذرة (6 شيكل)\nيقدم طوال اليوم",
        },
        price: 59,
      },
      {
        id: "dish_4_7",
        name: {
          he: "קפה ומאפה",
          en: "Coffee & Pastry",
          ru: "Кофе и выпечка",
          fr: "Café et pâtisserie",
          ar: "قهوة ومعجنات",
        },
        description: {
          he: "מאפה שקדים / שוקולד\nמוגש בכל שעות היום",
          en: "Almond / chocolate pastry\nServed all day",
          ru: "Миндальная / шоколадная выпечка\nПодается весь день",
          fr: "Pâtisserie aux amandes / chocolat\nServi toute la journée",
          ar: "معجنات لوز / شوكولاتة\nيقدم طوال اليوم",
        },
        price: 39,
      },
    ],
  },
  {
    id: "category_5",
    name: {
      he: "סלטים",
      en: "Salads",
      ru: "Салаты",
      fr: "Salades",
      ar: "سلطات",
    },
    description: {
      he: "טעמים של בריאות ורעננות",
      en: "Tastes of health and freshness",
      ru: "Вкусы здоровья и свежести",
      fr: "Saveurs de santé et fraîcheur",
      ar: "نكهات الصحة والانتعاش",
    },
    order: 3,
    thumbnail:
      "https://www.healthyseasonalrecipes.com/wp-content/uploads/2022/06/healthy-cobb-salad-steps-sq-026.jpg",
    dishes: [
      {
        id: "dish_5_1",
        name: {
          he: "סלט קיסר",
          en: "Caesar Salad",
          ru: "Салат Цезарь",
          fr: "Salade César",
          ar: "سلطة سيزر",
        },
        description: {
          he: "חסה קיסר, רוטב קיסר, בצל סגול, ביצה רכה, קרוטונים, פרמזן",
          en: "Romaine lettuce, Caesar dressing, purple onion, soft-boiled egg, croutons, parmesan",
          ru: "Салат ромэн, соус Цезарь, фиолетовый лук, яйцо всмятку, крутоны, пармезан",
          fr: "Laitue romaine, sauce César, oignon violet, œuf mollet, croûtons, parmesan",
          ar: "خس روماني، صلصة سيزر، بصل أرجواني، بيضة مسلوقة، خبز محمص، بارميزان",
        },
        price: 75,
      },
      {
        id: "dish_5_2",
        name: {
          he: "סלט חזה עוף",
          en: "Chicken Breast Salad",
          ru: "Салат с куриной грудкой",
          fr: "Salade au blanc de poulet",
          ar: "سلطة صدر الدجاج",
        },
        description: {
          he: "חזה עוף מתובל על הגריל, מבחר עלים רעננים, שרי, מלפפון, בצל סגול, בתיבול שמן זית ולימון",
          en: "Grilled seasoned chicken breast, mixed fresh greens, cherry tomatoes, cucumber, purple onion, olive oil & lemon dressing",
          ru: "Жареная приправленная куриная грудка, микс свежей зелени, помидоры черри, огурец, фиолетовый лук, заправка из оливкового масла и лимона",
          fr: "Blanc de poulet grillé assaisonné, mélange de verdures fraîches, tomates cerises, concombre, oignon violet, vinaigrette huile d'olive-citron",
          ar: "صدر دجاج متبل مشوي، خليط من الأوراق الخضراء الطازجة، طماطم كرز، خيار، بصل أرجواني، صلصة زيت الزيتون والليمون",
        },
        price: 79,
      },
      {
        id: "dish_5_3",
        name: {
          he: "סלט יווני",
          en: "Greek Salad",
          ru: "Греческий салат",
          fr: "Salade grecque",
          ar: "سلطة يونانية",
        },
        description: {
          he: "מבחר עלים רעננים, שרי, מלפפון, בצל סגול, בולגרית מגורדת, זיתי קלמטה, זעתר, בתיבול שמן זית ולימון",
          en: "Mixed fresh greens, cherry tomatoes, cucumber, purple onion, shredded Bulgarian cheese, Kalamata olives, za'atar, olive oil & lemon dressing",
          ru: "Микс свежей зелени, помидоры черри, огурец, фиолетовый лук, тёртый болгарский сыр, оливки каламата, заатар, заправка из оливкового масла и лимона",
          fr: "Mélange de verdures fraîches, tomates cerises, concombre, oignon violet, fromage bulgare râpé, olives Kalamata, za'atar, vinaigrette huile d'olive-citron",
          ar: "خليط من الأوراق الطازجة، طماطم كرز، خيار، بصل أرجواني، جبنة بلغارية مبشورة، زيتون كالاماتا، زعتر، صلصة زيت الزيتون والليمون",
        },
        price: 75,
      },
      {
        id: "dish_5_4",
        name: {
          he: "סלט חלומי",
          en: "Halloumi Salad",
          ru: "Салат с халуми",
          fr: "Salade halloumi",
          ar: "سلطة حلوم",
        },
        description: {
          he: "מבחר עלים רעננים, שרי, מלפפון, בצל סגול, רצועות גבינת חלומי, רוטב ויניגרט הדרים, פטריות מוקפצות בטריאקי מתקתק",
          en: "Mixed fresh greens, cherry tomatoes, cucumber, purple onion, halloumi strips, citrus vinaigrette, mushrooms sautéed in sweet teriyaki",
          ru: "Микс свежей зелени, помидоры черри, огурец, фиолетовый лук, полоски халуми, цитрусовый винегрет, грибы обжаренные в сладком терияки",
          fr: "Mélange de verdures fraîches, tomates cerises, concombre, oignon violet, lanières d'halloumi, vinaigrette aux agrumes, champignons sautés au teriyaki sucré",
          ar: "خليط من الأوراق الطازجة، طماطم كرز، خيار، بصل أرجواني، شرائح حلوم، صلصة خل حمضيات، فطر مقلي بصلصة تيرياكي حلوة",
        },
        price: 79,
      },
      {
        id: "dish_5_5",
        name: {
          he: "סלט עשבים",
          en: "Herb Salad",
          ru: "Салат с травами",
          fr: "Salade d'herbes",
          ar: "سلطة أعشاب",
        },
        description: {
          he: "מיקס עלים ועשבים, רוטב ויניגרט תפוח עץ ופקאן",
          en: "Mixed greens and herbs, apple cider vinaigrette & pecans",
          ru: "Микс зелени и трав, яблочно-сидровый винегрет и пекан",
          fr: "Mélange de verdures et herbes, vinaigrette au cidre de pomme et noix de pécan",
          ar: "خليط من الأوراق والأعشاب، صلصة خل التفاح والبيكان",
        },
        price: 69,
        recommended: true,
        vegan: true,
      },
    ],
  },
  {
    id: "category_6",
    name: {
      he: "איטלקי",
      en: "Italian",
      ru: "Итальянская кухня",
      fr: "Italien",
      ar: "إيطالي",
    },
    description: {
      he: "פיצות ופסטות",
      en: "Pizzas and pastas",
      ru: "Пиццы и пасты",
      fr: "Pizzas et pâtes",
      ar: "بيتزا ومعكرونة",
    },
    order: 4,
    thumbnail:
      "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2023-01-Caramelized-Tomato-Paste-Pasta%2F06-CARAMELIZED-TOMATO-PASTE-PASTA-039",
    dishes: [
      {
        id: "dish_6_1",
        name: {
          he: "פיצה YA•ME",
          en: "YA•ME Pizza",
          ru: "Пицца YA•ME",
          fr: "Pizza YA•ME",
          ar: "بيتزا YA•ME",
        },
        description: {
          he: "רוטב עגבניות, מוצרלה, בטטה צלויה, שום קונפי, פרמזן, נגיעות בלסמי מצומצם",
          en: "Tomato sauce, mozzarella, roasted sweet potato, garlic confit, parmesan, balsamic reduction drizzle",
          ru: "Томатный соус, моцарелла, жареный батат, чесночный конфи, пармезан, бальзамическая редукция",
          fr: "Sauce tomate, mozzarella, patate douce rôtie, confit d'ail, parmesan, filet de réduction balsamique",
          ar: "صلصة طماطم، موزاريلا، بطاطا حلوة مشوية، ثوم كونفي، بارميزان، رذاذ بلسمك مركز",
        },
        price: 79,
        recommended: true,
      },
      {
        id: "dish_6_2",
        name: {
          he: "פיצה מיקונוס",
          en: "Mykonos Pizza",
          ru: "Пицца Миконос",
          fr: "Pizza Mykonos",
          ar: "بيتزا ميكونوس",
        },
        description: {
          he: "רוטב עגבניות, מוצרלה, בצל סגול, זיתי קלמטה, גבינה בולגרית מגורדת",
          en: "Tomato sauce, mozzarella, purple onion, Kalamata olives, shredded Bulgarian cheese",
          ru: "Томатный соус, моцарелла, фиолетовый лук, оливки каламата, тёртый болгарский сыр",
          fr: "Sauce tomate, mozzarella, oignon violet, olives Kalamata, fromage bulgare râpé",
          ar: "صلصة طماطم، موزاريلا، بصل أرجواني، زيتون كالاماتا، جبنة بلغارية مبشورة",
        },
        price: 79,
      },
      {
        id: "dish_6_3",
        name: {
          he: "פיצה מרגריטה",
          en: "Margherita Pizza",
          ru: "Пицца Маргарита",
          fr: "Pizza Margherita",
          ar: "بيتزا مارغريتا",
        },
        description: {
          he: 'רוטב עגבניות, גבינת מוצרלה, בזיליקום טרי\nתוספות לבחירה: עגבנייה, פטה, זיתי קלמטה, בצל, פטריות טריות, תירס (6 ש"ח)',
          en: "Tomato sauce, mozzarella cheese, fresh basil\nOptional add-ons: tomato, feta, Kalamata olives, onion, fresh mushrooms, corn (6 NIS)",
          ru: "Томатный соус, сыр моцарелла, свежий базилик\nОпции: помидор, фета, оливки каламата, лук, свежие грибы, кукуруза (6 шек.)",
          fr: "Sauce tomate, fromage mozzarella, basilic frais\nSuppléments au choix : tomate, feta, olives Kalamata, oignon, champignons frais, maïs (6 NIS)",
          ar: "صلصة طماطم، جبنة موزاريلا، ريحان طازج\nإضافات اختيارية: طماطم، فيتا، زيتون كالاماتا، بصل، فطر طازج، ذرة (6 شيكل)",
        },
        price: 69,
      },
      {
        id: "dish_6_35",
        name: {
          he: "פסטה YA•ME",
          en: "YA•ME Pasta",
          ru: "Паста YA•ME",
          fr: "Pâtes YA•ME",
          ar: "معكرونة YA•ME",
        },
        description: {
          he: "פסטה פטוצ׳יני, רוטב שמנת, בטטה, ערמונים, פרמזן, בזיליקום טרי",
          en: "Fettuccine pasta, cream sauce, sweet potato, chestnuts, parmesan, fresh basil",
          ru: "Паста фетучини, сливочный соус, батат, каштаны, пармезан, свежий базилик",
          fr: "Pâtes fettuccine, sauce crème, patate douce, châtaignes, parmesan, basilic frais",
          ar: "معكرونة فيتوتشيني، صلصة كريمة، بطاطا حلوة، كستناء، بارميزان، ريحان طازج",
        },
        price: 79,
        recommended: true,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0063.jpg",
      },
      {
        id: "dish_6_4",
        name: {
          he: "אלפרדו גרנדה",
          en: "Alfredo Grande",
          ru: "Альфредо Гранде",
          fr: "Alfredo Grande",
          ar: "ألفريدو غراندي",
        },
        description: {
          he: "פסטה פטוצ'יני, רוטב שמנת, פטריות טריות, פרמזן, בזיליקום טרי",
          en: "Fettuccine pasta, cream sauce, fresh mushrooms, parmesan, fresh basil",
          ru: "Паста фетучини, сливочный соус, свежие грибы, пармезан, свежий базилик",
          fr: "Pâtes fettuccine, sauce crème, champignons frais, parmesan, basilic frais",
          ar: "معكرونة فيتوتشيني، صلصة كريمة، فطر طازج، بارميزان، ريحان طازج",
        },
        price: 74,
      },
      {
        id: "dish_6_5",
        name: {
          he: "פסטה רוזה",
          en: "Rosé Pasta",
          ru: "Паста Розе",
          fr: "Pâtes rosées",
          ar: "معكرونة روزيه",
        },
        description: {
          he: "פסטה פטוצ'יני, רוטב שמנת ועגבניות, פרמזן, בזיליקום טרי",
          en: "Fettuccine pasta, cream and tomato sauce, parmesan, fresh basil",
          ru: "Паста фетучини, сливочно-томатный соус, пармезан, свежий базилик",
          fr: "Pâtes fettuccine, sauce crème et tomate, parmesan, basilic frais",
          ar: "معكرونة فيتوتشيني، صلصة كريمة وطماطم، بارميزان، ريحان طازج",
        },
        price: 79,
      },
      {
        id: "dish_6_6",
        name: {
          he: "טורטליני פולנטה",
          en: "Polenta Tortellini",
          ru: "Тортеллини Полента",
          fr: "Tortellini polenta",
          ar: "تورتيليني بولنتا",
        },
        description: {
          he: "טורטליני ברוטב חמאת עגבניות ופרמזין",
          en: "Tortellini in tomato butter sauce and parmesan",
          ru: "Тортеллини в томатно-сливочном соусе с пармезаном",
          fr: "Tortellini dans une sauce beurre-tomate et parmesan",
          ar: "تورتيليني في صلصة زبدة الطماطم وبارميزان",
        },
        price: 75,
        recommended: true,
      },
    ],
  },
  {
    id: "category_7",
    name: {
      he: "קינוחים",
      en: "Desserts",
      ru: "Десерты",
      fr: "Desserts",
      ar: "حلويات",
    },
    description: {
      he: "רגע לפני שמסיימים, משהו מתוק",
      en: "A little something sweet before you finish",
      ru: "Немного сладкого перед концом трапезы",
      fr: "Un petit quelque chose de sucré pour terminer",
      ar: "شيء حلو قبل الختام",
    },
    order: 6,
    thumbnail:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/05/Chocolate-sandwich-cupcakes-4b30ada.jpg?quality=90&resize=708,643",
    dishes: [
      {
        id: "dish_7_1",
        name: {
          he: "עוגת גבינה באסקית",
          en: "Basque Cheesecake",
          ru: "Баскский чизкейк",
          fr: "Gâteau au fromage basque",
          ar: "تشيز كيك باسكي",
        },
        description: {
          he: "עוגת גבינה באסקית אפויה, עשירה ונימוחה על מצע עוגיות חמאה",
          en: "Baked Basque cheesecake, rich and creamy on a butter cookie base",
          ru: "Запечённый баскский чизкейк, насыщенный и нежный, на песочной основе",
          fr: "Gâteau au fromage basque cuit, riche et fondant sur base de biscuits au beurre",
          ar: "تشيز كيك باسكي مخبوز غني وكريمي على قاعدة بسكويت بالزبدة",
        },
        price: 59,
      },
      {
        id: "dish_7_2",
        name: {
          he: "עוגת גזר",
          en: "Carrot Cake",
          ru: "Морковный торт",
          fr: "Gâteau aux carottes",
          ar: "كيكة الجزر",
        },
        description: {
          he: "שכבות של עוגת גזר שביניהם קרם גבינה וניל ומעל קראמבל שוקולד לבן",
          en: "Layers of carrot cake with vanilla cream-cheese filling and white chocolate crumble",
          ru: "Слоёный морковный торт с ванильным крем-сыром и крамблом из белого шоколада",
          fr: "Couches de gâteau aux carottes, crème au fromage vanille et crumble au chocolat blanc",
          ar: "طبقات من كعكة الجزر مع كريمة جبن بالفانيليا وتغليفة كرامبل شوكولاتة بيضاء",
        },
        price: 59,
      },
      {
        id: "dish_7_3",
        name: {
          he: "פאדג' חמה",
          en: "Hot Fudge Cake",
          ru: "Горячий шоколадный фадж",
          fr: "Gâteau fudge chaud",
          ar: "كيكة فدج ساخنة",
        },
        description: {
          he: "עוגת שוקולד ביתית חמה ונימוחה, עשויה ללא קמח ומלאה בשוקולד מבפנים ומבחוץ",
          en: "Warm homemade flourless chocolate cake, rich and gooey inside and out",
          ru: "Тёплый домашний шоколадный торт без муки, насыщенный и тягучий внутри и снаружи",
          fr: "Gâteau au chocolat maison chaud, sans farine, riche et fondant à cœur",
          ar: "كعكة شوكولاتة منزلية ساخنة بدون دقيق، غنية ومليئة بالشوكولاتة من الداخل والخارج",
        },
        price: 59,
      },
      {
        id: "dish_7_4",
        name: {
          he: "סופלה אלפרדו",
          en: "Alfredo Soufflé",
          ru: "Суфле «Альфредо»",
          fr: "Soufflé Alfredo",
          ar: "سوفليه ألفريدو",
        },
        description: {
          he: "פונדנט שוקולד חם עם טראפל שוקולד בפנים, בציפוי של גנאש שוקולד חלב",
          en: "Warm chocolate fondant with chocolate truffle center, topped with milk chocolate ganache",
          ru: "Тёплый шоколадный фондан с трюфельной начинкой, покрытый ганашем из молочного шоколада",
          fr: "Fondant au chocolat chaud avec cœur truffe, nappé d'un glaçage ganache au chocolat au lait",
          ar: "فوندان شوكولاتة ساخن بحشوة ترافل، مغطى بجاناش شوكولاتة بالحليب",
        },
        price: 59,
      },
      {
        id: "dish_7_5",
        name: {
          he: "עוגת קוקיס קינדר",
          en: "Kinder Cookie Cake",
          ru: "Торт из печенья «Киндер»",
          fr: "Gâteau cookie Kinder",
          ar: "كيكة كوكيز كيندر",
        },
        description: {
          he: "משולש שכבות בצק עשוי קוקיס שוקו צ'יפס שביניהם גנאש קינדר",
          en: "Layered triangle of chocolate-chip cookie dough filled with Kinder ganache",
          ru: "Слоёный треугольник из теста печенья с шоколадной крошкой, с ганашем «Киндер» между слоями",
          fr: "Triangle de pâte à cookie aux pépites de chocolat, garni de ganache Kinder entre les couches",
          ar: "مثلث طبقات من عجينة كوكيز برقائق الشوكولاتة محشو بجاناش كيندر بين الطبقات",
        },
        price: 59,
      },
      {
        id: "dish_7_6",
        name: {
          he: "אבטיח",
          en: "Watermelon",
          ru: "Арбуз",
          fr: "Pastèque",
          ar: "بطيخ",
        },
        description: {
          he: "מוגש בעונה",
          en: "Served in season",
          ru: "Подаётся в сезон",
          fr: "Servi en saison",
          ar: "يُقدّم في الموسم",
        },
        price: 46,
      },
      {
        id: "dish_7_7",
        name: {
          he: "אבטיח בולגרית",
          en: "Watermelon with Bulgarian Cheese",
          ru: "Арбуз с болгарским сыром",
          fr: "Pastèque au fromage bulgare",
          ar: "بطيخ مع جبنة بلغارية",
        },
        description: {
          he: "מוגש בעונה",
          en: "Served in season",
          ru: "Подаётся в сезон",
          fr: "Servi en saison",
          ar: "يُقدّم في الموسم",
        },
        price: 56,
      },
    ],
  },
  {
    id: "category_8",
    name: {
      he: "שתיה חמה",
      en: "Hot Drinks",
      ru: "Горячие напитки",
      fr: "Boissons chaudes",
      ar: "مشروبات ساخنة",
    },
    description: {
      he: "תוספת חלב שקדים / סויה / שיבולת שועל: 3 ש״ח",
      en: "Almond / soy / oat milk extra: 3 NIS",
      ru: "Добавка миндального / соевого / овсяного молока: 3 шек.",
      fr: "Supplément lait d'amande / soja / avoine: 3 NIS",
      ar: "إضافة حليب لوز / صويا / شوفان: 3 شيكل",
    },
    thumbnail:
      "https://www.americanolounge.com/wp-content/uploads/2024/08/What-is-American-style-coffee_270222935.webp",
    order: 7,
    dishes: [
      {
        id: "dish_8_1",
        name: {
          he: "אספרסו",
          en: "Espresso",
          ru: "Эспрессо",
          fr: "Espresso",
          ar: "إسبريسو",
        },
        description: {
          he: "קצר / ארוך",
          en: "Short / long",
          ru: "Короткий / длинный",
          fr: "Court / long",
          ar: "قصير / طويل",
        },
        price: 12,
      },
      {
        id: "dish_8_2",
        name: {
          he: "אספרסו כפול",
          en: "Double Espresso",
          ru: "Двойной эспрессо",
          fr: "Espresso double",
          ar: "إسبريسو مزدوج",
        },
        description: {
          he: "קצר / ארוך",
          en: "Short / long",
          ru: "Короткий / длинный",
          fr: "Court / long",
          ar: "قصير / طويل",
        },
        price: 14,
      },
      {
        id: "dish_8_3",
        name: {
          he: "מקיאטו",
          en: "Macchiato",
          ru: "Маккиато",
          fr: "Macchiato",
          ar: "ماكياتو",
        },
        description: {
          he: "קצר / ארוך",
          en: "Short / long",
          ru: "Короткий / длинный",
          fr: "Court / long",
          ar: "قصير / طويل",
        },
        price: 12,
      },
      {
        id: "dish_8_4_small",
        name: {
          he: "קפוצ׳ינו קטן",
          en: "Small Cappuccino",
          ru: "Маленький капучино",
          fr: "Petit cappuccino",
          ar: "كابتشينو صغير",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 14,
      },
      {
        id: "dish_8_4_large",
        name: {
          he: "קפוצ׳ינו גדול",
          en: "Large Cappuccino",
          ru: "Большой капучино",
          fr: "Grand cappuccino",
          ar: "كابتشينو كبير",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 18,
      },
      {
        id: "dish_8_5",
        name: {
          he: "נס על חלב",
          en: "Instant Coffee with Milk",
          ru: "Растворимый кофе с молоком",
          fr: "Café instantané au lait",
          ar: "نسكافيه مع حليب",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 17,
      },
      {
        id: "dish_8_6",
        name: {
          he: "נס קפה / אמריקנו",
          en: "Instant Coffee / Americano",
          ru: "Растворимый кофе / Американо",
          fr: "Café instantané / Americano",
          ar: "نسكافيه / أمريكانو",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 14,
      },
      {
        id: "dish_8_7",
        name: {
          he: "קפה שחור",
          en: "Black Coffee (Turkish)",
          ru: "Чёрный кофе (по-восточному)",
          fr: "Café noir (turc)",
          ar: "قهوة سوداء (قهوة عربية/تركية)",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 11,
      },
      {
        id: "dish_8_8",
        name: {
          he: "שוקו חם",
          en: "Hot Chocolate",
          ru: "Горячий шоколад",
          fr: "Chocolat chaud",
          ar: "شوكولاتة ساخنة",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 14,
      },
      {
        id: "dish_8_9",
        name: {
          he: "שוקו פרלינים",
          en: "Praline Hot Chocolate",
          ru: "Горячий шоколад с пралине",
          fr: "Chocolat chaud praliné",
          ar: "شوكولاتة ساخنة برالين",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 22,
      },
      {
        id: "dish_8_10",
        name: {
          he: "תה",
          en: "Tea",
          ru: "Чай",
          fr: "Thé",
          ar: "شاي",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 12,
      },
      {
        id: "dish_8_11",
        name: {
          he: "תה נענע",
          en: "Mint Tea",
          ru: "Мятный чай",
          fr: "Thé à la menthe",
          ar: "شاي نعناع",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 14,
      },
      {
        id: "dish_8_12",
        name: {
          he: "סיידר חם",
          en: "Hot Cider",
          ru: "Горячий сидр",
          fr: "Cidre chaud",
          ar: "سيدر ساخن",
        },
        description: {
          he: "תוספת יין: 8 ש״ח",
          en: "Wine add-on: 8 NIS",
          ru: "Добавить вино: 8 шек.",
          fr: "Supplément vin: 8 NIS",
          ar: "إضافة نبيذ: 8 شيكل",
        },
        price: 22,
      },
    ],
  },
  {
    id: "category_9",
    name: {
      he: "שתיה קרה",
      en: "Cold Drinks",
      ru: "Холодные напитки",
      fr: "Boissons froides",
      ar: "مشروبات باردة",
    },
    description: {
      he: "שתיה קרה",
      en: "Cold beverages",
      ru: "Холодные напитки",
      fr: "Boissons froides",
      ar: "مشروبات باردة",
    },
    thumbnail:
      "https://gadegal-homestay.himwebx.com/wp-content/uploads/2023/10/cold-drink.jpeg",
    order: 8,
    dishes: [
      {
        id: "dish_9_1",
        name: {
          he: "שתיה קלה",
          en: "Soft Drinks",
          ru: "Газированные напитки",
          fr: "Sodas",
          ar: "مشروبات غازية",
        },
        description: {
          he: "קוקה קולה, קולה זירו, ספרייט, ספרייט זירו, פאנטה, פיוז טי",
          en: "Coca-Cola, Coke Zero, Sprite, Sprite Zero, Fanta, Fuze Tea",
          ru: "Coca-Cola, Coke Zero, Sprite, Sprite Zero, Fanta, Fuze Tea",
          fr: "Coca-Cola, Coke Zero, Sprite, Sprite Zero, Fanta, Fuze Tea",
          ar: "كوكاكولا، كولا زيرو، سبرايت، سبرايت زيرو، فانتا، فيوز تي",
        },
        price: 15,
      },
      {
        id: "dish_9_2",
        name: {
          he: "סודה / מים מינרליים",
          en: "Soda / Mineral Water",
          ru: "Содовая / минеральная вода",
          fr: "Soda / eau minérale",
          ar: "صودا / ماء معدني",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 12,
      },
      {
        id: "dish_9_3",
        name: {
          he: "נביעות בטעמים",
          en: "Flavoured Spring Water",
          ru: "Ароматизированная родниковая вода",
          fr: "Eau de source aromatisée",
          ar: "ماء نبع منكه",
        },
        description: {
          he: "אפרסק / ענבים / תפוח",
          en: "Peach / grape / apple",
          ru: "Персик / виноград / яблоко",
          fr: "Pêche / raisin / pomme",
          ar: "خوخ / عنب / تفاح",
        },
        price: 15,
      },
      {
        id: "dish_9_4",
        name: {
          he: "פריגת",
          en: "Prigat",
          ru: "Prigat",
          fr: "Prigat",
          ar: "بريغات",
        },
        description: {
          he: "ענבים / תפוזים",
          en: "Grape / orange",
          ru: "Виноград / апельсин",
          fr: "Raisin / orange",
          ar: "عنب / برتقال",
        },
        price: 16,
      },
      {
        id: "dish_9_5",
        name: {
          he: "לימונדה / לימונענע",
          en: "Lemonade / Mint Lemonade",
          ru: "Лимонад / лимонад с мятой",
          fr: "Limonade / limonade à la menthe",
          ar: "ليمونادة / ليمونادة بالنعناع",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 16,
      },
      {
        id: "dish_9_6",
        name: {
          he: "קנקן לימונענע",
          en: "Pitcher of Mint Lemonade",
          ru: "Кувшин лимонада с мятой",
          fr: "Pichet de limonade à la menthe",
          ar: "إبريق ليمونادة بالنعناع",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 42,
      },
      {
        id: "dish_9_7",
        name: {
          he: "מיץ סחוט טרי",
          en: "Freshly Squeezed Juice",
          ru: "Свежевыжатый сок",
          fr: "Jus fraîchement pressé",
          ar: "عصير طازج",
        },
        description: {
          he: "תפוזים / גזר / תפוגזר",
          en: "Orange / carrot / orange–carrot",
          ru: "Апельсин / морковь / апельсин-морковь",
          fr: "Orange / carotte / orange-carotte",
          ar: "برتقال / جزر / برتقال-جزر",
        },
        price: 22,
      },
      {
        id: "dish_9_8",
        name: {
          he: "קפה קר",
          en: "Iced Coffee",
          ru: "Холодный кофе",
          fr: "Café glacé",
          ar: "قهوة باردة",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 18,
      },
      {
        id: "dish_9_9",
        name: {
          he: "מאלטי",
          en: "Malty Drink",
          ru: "Солодовый напиток",
          fr: "Boisson maltée",
          ar: "مشروب مالت",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 19,
      },
      {
        id: "dish_9_10",
        name: {
          he: "משקה אנרגיה",
          en: "Energy Drink",
          ru: "Энергетический напиток",
          fr: "Boisson énergisante",
          ar: "مشروب طاقة",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 16,
      },
      {
        id: "dish_9_11",
        name: {
          he: "מים מינרליים Ferrarelle",
          en: "Ferrarelle Mineral Water",
          ru: "Минеральная вода Ferrarelle",
          fr: "Eau minérale Ferrarelle",
          ar: "مياه معدنية Ferrarelle",
        },
        description: {
          he: "750 מ״ל",
          en: "750 ml",
          ru: "750 мл",
          fr: "750 ml",
          ar: "750 مل",
        },
        price: 32,
      },
    ],
  },
  {
    id: "category_10",
    name: {
      he: "מרעננים",
      en: "Refreshing Drinks",
      ru: "Освежающие напитки",
      fr: "Boissons rafraîchissantes",
      ar: "مشروبات منعشة",
    },
    description: {
      he: "משקאות קפואים מרעננים, שילוב מושלם של פירות וקרח",
      en: "Refreshing frozen drinks, a perfect blend of fruit and ice",
      ru: "Освежающие замороженные напитки, идеальное сочетание фруктов и льда",
      fr: "Boissons glacées rafraîchissantes, un mélange parfait de fruits et de glace",
      ar: "مشروبات مثلجة منعشة، مزيج مثالي من الفاكهة والثلج",
    },
    order: 9,
    thumbnail:
      "https://hips.hearstapps.com/hmg-prod/images/delish-how-to-make-a-smoothie-horizontal-1542310071.png?crop=1xw:0.843328335832084xh;center,top&resize=1200:*",
    dishes: [
      {
        id: "dish_10_1",
        name: {
          he: "אייס קפה",
          en: "Iced Coffee",
          ru: "Холодный кофе",
          fr: "Café glacé",
          ar: "قهوة مثلجة",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 32,
      },
      {
        id: "dish_10_2",
        name: {
          he: "גרניטה לימונענע",
          en: "Mint Lemon Granita",
          ru: "Гранита с лимоном и мятой",
          fr: "Granité citron-menthe",
          ar: "جرانيتا بالليمون والنعناع",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 19,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0147.jpg",
      },
      {
        id: "dish_10_3",
        name: {
          he: "פרש מנגו",
          en: "Fresh Mango",
          ru: "Свежий манго",
          fr: "Mangue fraîche",
          ar: "مانجو طازج",
        },
        description: {
          he: "[translate:פרי מנגו ונענע טריה מוגש גרוס]",
          en: "Fresh mango and mint fruit, served crushed",
          ru: "Свежий манго и мята, подаются дроблеными",
          fr: "Fruit de mangue et menthe fraîche, servi écrasé",
          ar: "فاكهة المانجو والنعناع الطازج، تُقدّم مهروسة",
        },
        price: 38,
      },
      {
        id: "dish_10_4",
        name: {
          he: "מילקשייק",
          en: "Milkshake",
          ru: "Молочный коктейль",
          fr: "Milkshake",
          ar: "ميلك شيك",
        },
        description: {
          he: "בטעמי שוקו, וניל, ריבת חלב",
          en: "In chocolate, vanilla, dulce de leche flavors",
          ru: "Со вкусами шоколада, ванили, дульсе де лече",
          fr: "Aux saveurs chocolat, vanille, confiture de lait",
          ar: "بنكهات الشوكولاتة، الفانيليا، دولسي دي ليشي",
        },
        price: 38,
      },
      {
        id: "dish_10_5",
        name: {
          he: "שייק פירות",
          en: "Fruit Shake",
          ru: "Фруктовый смузи",
          fr: "Smoothie aux fruits",
          ar: "عصير فواكه",
        },
        description: {
          he: "בטעמי תות, בננה, תמר, מנגו",
          en: "With strawberry, banana, date, mango flavors",
          ru: "Со вкусами клубники, банана, фиников, манго",
          fr: "Aux saveurs fraise, banane, datte, mangue",
          ar: "بنكات الفراولة، الموز، التمر، المانجو",
        },
        price: 38,
      },
    ],
  },
  {
    id: "category_12",
    name: {
      he: "יינות",
      en: "Wines",
      ru: "Вина",
      fr: "Vins",
      ar: "نبيذ",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 10,
    thumbnail:
      "https://cdn.shopify.com/s/files/1/0278/8642/0047/files/11_Types_of_Wine_480x480.jpg?v=1711203013",
    dishes: [
      {
        id: "dish_12_1",
        name: {
          he: "הר חרמון לבן",
          en: "Mt. Hermon White",
          ru: "Хар Хермон белое",
          fr: "Mont Hermon Blanc",
          ar: "جبل حرمون أبيض",
        },
        description: {
          he: "מחיר לכוס | מחיר לבקבוק: 159",
          en: "Glass price | Bottle: 159 NIS",
          ru: "Цена бокала | Бутылка: 159 шек.",
          fr: "Prix verre | Bouteille: 159 NIS",
          ar: "سعر الكأس | الزجاجة: 159 شيكل",
        },
        price: 56,
      },
      {
        id: "dish_12_2",
        name: {
          he: "הר חרמון אדום",
          en: "Mt. Hermon Red",
          ru: "Хар Хермон красное",
          fr: "Mont Hermon Rouge",
          ar: "جبل حرمون أحمر",
        },
        description: {
          he: "מחיר לכוס | מחיר לבקבוק: 159",
          en: "Glass price | Bottle: 159 NIS",
          ru: "Цена бокала | Бутылка: 159 шек.",
          fr: "Prix verre | Bouteille: 159 NIS",
          ar: "سعر الكأس | الزجاجة: 159 شيكل",
        },
        price: 56,
      },
      {
        id: "dish_12_3",
        name: {
          he: "גוורץ",
          en: "Gewürztraminer",
          ru: "Гевюрцтраминер",
          fr: "Gewürztraminer",
          ar: "جفورتسـترامينر",
        },
        description: {
          he: "מחיר לכוס | מחיר לבקבוק: 139",
          en: "Glass price | Bottle: 139 NIS",
          ru: "Цена бокала | Бутылка: 139 шек.",
          fr: "Prix verre | Bouteille: 139 NIS",
          ar: "سعر الكأس | الزجاجة: 139 شيكل",
        },
        price: 54,
      },
      {
        id: "dish_12_4",
        name: {
          he: "רוזה רקנאטי",
          en: "Recanati Rosé",
          ru: "Реканати розовое",
          fr: "Rosé Recanati",
          ar: "ريكاناتي روزي",
        },
        description: {
          he: "מחיר לכוס | מחיר לבקבוק: 139",
          en: "Glass price | Bottle: 139 NIS",
          ru: "Цена бокала | Бутылка: 139 шек.",
          fr: "Prix verre | Bouteille: 139 NIS",
          ar: "سعر الكأس | الزجاجة: 139 شيكل",
        },
        price: 54,
      },
      {
        id: "dish_12_5",
        name: {
          he: "שאבלי",
          en: "Chablis",
          ru: "Шабли",
          fr: "Chablis",
          ar: "شابلي",
        },
        description: {
          he: "מחיר לכוס | מחיר לבקבוק: 259",
          en: "Glass price | Bottle: 259 NIS",
          ru: "Цена бокала | Бутылка: 259 шек.",
          fr: "Prix verre | Bouteille: 259 NIS",
          ar: "سعر الكأس | الزجاجة: 259 شيكل",
        },
        price: 59,
      },
    ],
  },
  {
    id: "category_13",
    name: {
      he: "בירות מהחבית",
      en: "Draft Beers",
      ru: "Пиво из бака",
      fr: "Bière pression",
      ar: "بيرة من الخامة",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 11,
    thumbnail:
      "https://www.tastingtable.com/img/gallery/why-draft-beer-tastes-better-than-bottled/the-tasting-experience-1648062930.jpg",
    dishes: [
      {
        id: "dish_13_1",
        name: {
          he: "ווינשטפן",
          en: "Weinstefan",
          ru: "Вайнштефан",
          fr: "Weinstefan",
          ar: "واينشتابان",
        },
        description: {
          he: "חצי ליטר | שליש ליטר: 39",
          en: "0.5L | 1/3L: 39 NIS",
          ru: "0.5л | 1/3л: 39 шек.",
          fr: "0.5L | 1/3L: 39 NIS",
          ar: "0.5ل | 1/3ل: 39 شيكل",
        },
        price: 45,
      },
      {
        id: "dish_13_2",
        name: {
          he: "סובורג",
          en: "Sovborg",
          ru: "Совборг",
          fr: "Sovborg",
          ar: "سوفبورغ",
        },
        description: {
          he: "חצי ליטר | שליש ליטר: 36",
          en: "0.5L | 1/3L: 36 NIS",
          ru: "0.5л | 1/3л: 36 шек.",
          fr: "0.5L | 1/3L: 36 NIS",
          ar: "0.5ل | 1/3ل: 36 شيكل",
        },
        price: 42,
      },
      {
        id: "dish_13_3",
        name: {
          he: "קרלסברג",
          en: "Carlsberg",
          ru: "Карлсберг",
          fr: "Carlsberg",
          ar: "كارلسبرغ",
        },
        description: {
          he: "חצי ליטר | שליש ליטר: 36",
          en: "0.5L | 1/3L: 36 NIS",
          ru: "0.5л | 1/3л: 36 шек.",
          fr: "0.5L | 1/3L: 36 NIS",
          ar: "0.5ل | 1/3ل: 36 شيكل",
        },
        price: 42,
      },
      {
        id: "dish_13_4",
        name: {
          he: "שנדי",
          en: "Shandy",
          ru: "Шенди",
          fr: "Shandy",
          ar: "شاندي",
        },
        description: {
          he: "חצי ליטר | שליש ליטר: 36",
          en: "0.5L | 1/3L: 36 NIS",
          ru: "0.5л | 1/3л: 36 шек.",
          fr: "0.5L | 1/3L: 36 NIS",
          ar: "0.5ل | 1/3ل: 36 شيكل",
        },
        price: 42,
      },
    ],
  },
  {
    id: "category_14",
    name: {
      he: "בירות בבקבוק",
      en: "Bottled Beers",
      ru: "Пиво в бутылках",
      fr: "Bière en bouteille",
      ar: "بيرة في زجاجات",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 12,
    thumbnail:
      "https://thumbs.dreamstime.com/b/bottles-famous-global-beer-brands-poznan-pol-mar-including-heineken-becks-bud-miller-corona-stella-artois-san-miguel-143170558.jpg",
    dishes: [
      {
        id: "dish_14_1",
        name: {
          he: "קורונה",
          en: "Corona",
          ru: "Корона",
          fr: "Corona",
          ar: "كورونا",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 38,
      },
      {
        id: "dish_14_2",
        name: {
          he: "היינקן",
          en: "Heineken",
          ru: "Хайнекен",
          fr: "Heineken",
          ar: "هاينكن",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 36,
      },
      {
        id: "dish_14_3",
        name: {
          he: "בלאנك",
          en: "Blonde",
          ru: "Блонд",
          fr: "Blonde",
          ar: "بلوند",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 36,
      },
      {
        id: "dish_14_4",
        name: {
          he: "קסטיל רוז",
          en: "Castiel Rosé",
          ru: "Кастиэль розовое",
          fr: "Castiel Rosé",
          ar: "كاستييل روزي",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 45,
      },
      {
        id: "dish_14_5",
        name: {
          he: "סמירנוף אייס",
          en: "Smirnoff Ice",
          ru: "Смирнофф Айс",
          fr: "Smirnoff Ice",
          ar: "سميرنوف آيس",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 38,
      },
      {
        id: "dish_14_6",
        name: {
          he: "סומרסבי",
          en: "Somersby",
          ru: "Сомерсби",
          fr: "Somersby",
          ar: "سومرسبي",
        },
        description: {
          he: "תפוח / פירות יער",
          en: "Apple / berries",
          ru: "Яблоко / ягоды",
          fr: "Pomme / baies",
          ar: "تفاح / توت",
        },
        price: 38,
      },
      {
        id: "dish_14_7",
        name: {
          he: "בריזר",
          en: "Brewer",
          ru: "Бризер",
          fr: "Brewer",
          ar: "بريزر",
        },
        description: {
          he: "אבטיח / אננס",
          en: "Watermelon / pineapple",
          ru: "Арбуз / ананас",
          fr: "Pastèque / ananas",
          ar: "بطيخ / أناناس",
        },
        price: 38,
      },
    ],
  },
  {
    id: "category_15",
    name: {
      he: "קוקטיילים קלאסיים",
      en: "Classic Cocktails",
      ru: "Классические коктейли",
      fr: "Cocktails classiques",
      ar: "كوكتيلات كلاسيكية",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 13,
    thumbnail:
      "https://demitris.com/cdn/shop/articles/Untitled_design_-_2025-04-17T130659.845.png?v=1744916832",
    dishes: [
      {
        id: "dish_15_1",
        name: {
          he: "מוחיטו",
          en: "Mojito",
          ru: "Мохито",
          fr: "Mojito",
          ar: "موخيتو",
        },
        description: {
          he: "רום, ספרייט, נענע, לימון, סוכר חום",
          en: "Rum, Sprite, mint, lemon, brown sugar",
          ru: "Ром, спрайт, мята, лимон, коричневый сахар",
          fr: "Rhum, Sprite, menthe, citron, sucre brun",
          ar: "روم، سبرايت، نعناع، ليمون، سكر بني",
        },
        price: 59,
      },
      {
        id: "dish_15_3",
        name: {
          he: "אפרול שפריץ",
          en: "Aperol Spritz",
          ru: "Апероль Спритц",
          fr: "Aperol Spritz",
          ar: "أبيrol سبریتز",
        },
        description: {
          he: "אפרול, קאווה, סודה, סלייס תפוז",
          en: "Aperol, cava, soda, orange slice",
          ru: "Апероль, кавa, содовая, долька апельсина",
          fr: "Aperol, cava, soda, tranche d'orange",
          ar: "أبيrol، كافا، صودا، شريحة برتقال",
        },
        price: 59,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0204.jpg",
      },
      {
        id: "dish_15_4",
        name: {
          he: "ג'ין טוניק",
          en: "Gin Tonic",
          ru: "Джин-тоник",
          fr: "Gin Tonic",
          ar: "جين تونيك",
        },
        description: {
          he: "ג׳ין, מי טוניק, נענע, קליפת מלפפון",
          en: "Gin, tonic water, mint, cucumber peel",
          ru: "Джин, тоник, мята, цедра огурца",
          fr: "Gin, eau tonique, menthe, zeste concombre",
          ar: "جين، ماء تونيك، نعناع، قشر خيار",
        },
        price: 59,
      },
      {
        id: "dish_15_5",
        name: {
          he: "אייס לימונארק",
          en: "Iced Limonarq",
          ru: "Лимонарк со льдом",
          fr: "Limonarq glacé",
          ar: "ليمونارك مثلج",
        },
        description: {
          he: "ערק, לימונים, נענע טריה. מוגש גרוס",
          en: "Arak, lemons, fresh mint. Served crushed",
          ru: "Арак, лимоны, свежая мята. Подается дробленым",
          fr: "Arak, citrons, menthe fraîche. Servi pilé",
          ar: "عرق، ليمون، نعناع طازج. يُقدم مهروس",
        },
        price: 59,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0147.jpg",
      },
      {
        id: "dish_15_6",
        name: {
          he: "נגרוני",
          en: "Negroni",
          ru: "Негрони",
          fr: "Negroni",
          ar: "نيغروني",
        },
        description: {
          he: "ג׳ין, קמפרי, מרטיני וורמוט אדום, מיץ תפוזים",
          en: "Gin, Campari, red Martini vermouth, orange juice",
          ru: "Джин, Кампари, красный вермут Мартини, апельсиновый сок",
          fr: "Gin, Campari, vermouth Martini rouge, jus d'orange",
          ar: "جين، كامباري، فермوث مارتيني أحمر، عصير برتقال",
        },
        price: 59,
      },
    ],
  },
  {
    id: "category_16",
    name: {
      he: "קוקטיילים YA-ME",
      en: "YA-ME Cocktails",
      ru: "Коктейли YA-ME",
      fr: "Cocktails YA-ME",
      ar: "كوكتيلات YA-ME",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 14,
    thumbnail:
      "https://demitris.com/cdn/shop/articles/Untitled_design_-_2025-04-17T130659.845.png?v=1744916832",
    dishes: [
      {
        id: "dish_16_1",
        name: {
          he: "מונאקו",
          en: "Monaco",
          ru: "Монако",
          fr: "Monaco",
          ar: "موناكو",
        },
        description: {
          he: "וודקה, קוקטייל ליצי, לימונדה, פירות יער",
          en: "Vodka, lychee cocktail, lemonade, berries",
          ru: "Водка, коктейль личи, лимонад, ягоды",
          fr: "Vodka, cocktail lychee, limonade, baies",
          ar: "فودكا، كوكتيل ليتشي، ليمونادا، توت",
        },
        price: 65,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0107.jpg",
      },
      {
        id: "dish_16_11",
        name: {
          he: "קו-טאו",
          en: "Ko-Tao",
          ru: "Ко-Тао",
          fr: "Ko-Tao",
          ar: "كو-تاو",
        },
        description: {
          he: "טקילה, מנגו קפוא, מונין מנגו, קוקטייל ליצ׳י",
          en: "Tequila, frozen mango, Monin mango, lychee cocktail",
          ru: "Текила, замороженный манго, сироп манго Monin, коктейль личи",
          fr: "Tequila, mangue congelée, Monin mangue, cocktail lychee",
          ar: "تيكيلا، مانجو مجمد، مونين مانجو، كوكتيل ليتشي",
        },
        price: 65,
        thumbnail:
          "https://vpjgxnutcrreojzqewaw.supabase.co/storage/v1/object/public/images/IMG_0161.jpg",
      },
      {
        id: "dish_16_2",
        name: {
          he: "מיאמי בריז'",
          en: "Miami Breeze",
          ru: "Майами Бриз",
          fr: "Miami Breeze",
          ar: "نسيم ميامي",
        },
        description: {
          he: "ג׳ין, ספרייט, ריבת פירות יער, נענע ולימון",
          en: "Gin, Sprite, berry jam, mint and lemon",
          ru: "Джин, спрайт, джем из ягод, мята и лимон",
          fr: "Gin, Sprite, confiture baies, menthe et citron",
          ar: "جين، سبرايت، مربى توت، نعناع وليمون",
        },
        price: 65,
      },
      {
        id: "dish_16_3",
        name: {
          he: "טולום",
          en: "Tulum",
          ru: "Тулум",
          fr: "Tulum",
          ar: "تولوم",
        },
        description: {
          he: "טקילה, גרנדין, מיץ תפוזים, סלייס תפוז",
          en: "Tequila, grenadine, orange juice, orange slice",
          ru: "Текила, гренадин, апельсиновый сок, долька апельсина",
          fr: "Tequila, grenadine, jus d'orange, tranche d'orange",
          ar: "تيكيلا، غرنادين، عصير برتقال، شريحة برتقال",
        },
        price: 65,
      },
    ],
  },
  {
    id: "category_17",
    name: {
      he: "וויסקי",
      en: "Whiskey",
      ru: "Виски",
      fr: "Whisky",
      ar: "ويسكي",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 15,
    thumbnail:
      "https://minuman.com/cdn/shop/articles/061022---Get-Familiar-with-Different-Types-of-Whisky_dd355a17-b1d7-4261-9f0a-9d86e8b19399.jpg?v=1749691372",
    dishes: [
      {
        id: "dish_17_1",
        name: {
          he: "ג׳וני ווקר בלאק לייבל",
          en: "Johnnie Walker Black Label",
          ru: "Джонни Уолкер Блэк Лейбл",
          fr: "Johnnie Walker Black Label",
          ar: "جوني ووكر بلاك ليبل",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 59,
      },
      {
        id: "dish_17_2",
        name: {
          he: "שיבס",
          en: "Chivas",
          ru: "Чивас",
          fr: "Chivas",
          ar: "تشيفاز",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 59,
      },
      {
        id: "dish_17_3",
        name: {
          he: "ג'וני ווקר גולד לייבל",
          en: "Johnnie Walker Gold Label",
          ru: "Джонни Уолкер Голд Лейбл",
          fr: "Johnnie Walker Gold Label",
          ar: "جوني ووكر جولد ليبل",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
    ],
  },
  {
    id: "category_18",
    name: {
      he: "וודקה",
      en: "Vodka",
      ru: "Водка",
      fr: "Vodka",
      ar: "فودكا",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 16,
    thumbnail:
      "https://minuman.com/cdn/shop/articles/061022---Get-Familiar-with-Different-Types-of-Whisky_dd355a17-b1d7-4261-9f0a-9d86e8b19399.jpg?v=1749691372",
    dishes: [
      {
        id: "dish_18_1",
        name: {
          he: "פינלנדיה",
          en: "Finlandia",
          ru: "Финляндия",
          fr: "Finlandia",
          ar: "فينلانديا",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 59,
      },
      {
        id: "dish_18_3",
        name: {
          he: "גרייגוס",
          en: "Grey Goose",
          ru: "Грей Гус",
          fr: "Grey Goose",
          ar: "غري غوس",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
      {
        id: "dish_18_4",
        name: {
          he: "ואן גוך",
          en: "Van Gogh",
          ru: "Ван Гог",
          fr: "Van Gogh",
          ar: "فان جوخ",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
      {
        id: "dish_18_5",
        name: {
          he: "בלוודר",
          en: "Belvedere",
          ru: "Бельведер",
          fr: "Belvedere",
          ar: "بيلفيدير",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
    ],
  },
  {
    id: "category_19",
    name: {
      he: "טקילה",
      en: "Tequila",
      ru: "Текила",
      fr: "Tequila",
      ar: "تيكيلا",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 17,
    thumbnail:
      "https://minuman.com/cdn/shop/articles/061022---Get-Familiar-with-Different-Types-of-Whisky_dd355a17-b1d7-4261-9f0a-9d86e8b19399.jpg?v=1749691372",
    dishes: [
      {
        id: "dish_19_1",
        name: {
          he: "קוורבו נולד",
          en: "Cuervo Especial",
          ru: "Куэрво Эспесиал",
          fr: "Cuervo Especial",
          ar: "كويرفو إسبيشال",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 52,
      },
      {
        id: "dish_19_3",
        name: {
          he: "פטרון קלאסי",
          en: "Patron Classic",
          ru: "Патрон Классик",
          fr: "Patron Classic",
          ar: "باترون كلاسيك",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
    ],
  },
  {
    id: "category_20",
    name: {
      he: "קוניאק",
      en: "Cognac",
      ru: "Коньяк",
      fr: "Cognac",
      ar: "كونياك",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 18,
    thumbnail:
      "https://minuman.com/cdn/shop/articles/061022---Get-Familiar-with-Different-Types-of-Whisky_dd355a17-b1d7-4261-9f0a-9d86e8b19399.jpg?v=1749691372",
    dishes: [
      {
        id: "dish_20_1",
        name: {
          he: "הנסי",
          en: "Hennessy",
          ru: "Хеннесси",
          fr: "Hennessy",
          ar: "هينيسي",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
      {
        id: "dish_20_2",
        name: {
          he: "רמי מרטן",
          en: "Rémy Martin",
          ru: "Реми Мартен",
          fr: "Rémy Martin",
          ar: "ريمي مارتان",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 69,
      },
    ],
  },
  {
    id: "category_21",
    name: {
      he: "אניס",
      en: "Anise",
      ru: "Анис",
      fr: "Anis",
      ar: "يانسون",
    },
    description: {
      he: "מכירה או הגשה של משקאות חריפים למי שטרם מלאו לו 18 אסורה",
      en: "Sale or serving of alcoholic beverages to minors under 18 prohibited",
      ru: "Продажа или подача алкоголя лицам младше 18 лет запрещена",
      fr: "Vente ou service de boissons alcoolisées aux mineurs de moins de 18 ans interdit",
      ar: "ممنوع بيع أو تقديم المشروبات الكحولية لمن هم دون 18 عاماً",
    },
    order: 19,
    thumbnail:
      "https://minuman.com/cdn/shop/articles/061022---Get-Familiar-with-Different-Types-of-Whisky_dd355a17-b1d7-4261-9f0a-9d86e8b19399.jpg?v=1749691372",
    dishes: [
      {
        id: "dish_21_1",
        name: {
          he: "ערק עלית",
          en: "Elite Arak",
          ru: "Элитный Арак",
          fr: "Arak Elite",
          ar: "عرق إيليت",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 49,
      },
      {
        id: "dish_21_2",
        name: {
          he: "אוזו פלומרי",
          en: "Ouzo Plomari",
          ru: "Узо Пломари",
          fr: "Ouzo Plomari",
          ar: "أوزو بلوماري",
        },
        description: {
          he: "",
          en: "",
          ru: "",
          fr: "",
          ar: "",
        },
        price: 49,
      },
    ],
  },
];
