import type { Metadata } from "next";
import { Karantina, Open_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const karantina = Karantina({
  variable: "--font-karantina",
  subsets: ["latin"],
  weight: "300",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karantina.variable} ${openSans.variable} antialiased`}
      >
        <main className="flex flex-col items-center gap-[32px] row-start-2 bg-gradient-to-b from-blue-100 to-white h-screen">
          <Link href="/">
            <Image
              src="/logo.svg"
              alt="logo"
              width={240}
              height={80}
              priority
              className="mt-6"
            />
          </Link>
          {children}
        </main>
      </body>
    </html>
  );
}
